plugins {
    id 'net.fabricmc.fabric-loom' version '1.18.2'
}

version = project.mod_version
group = project.maven_group

base { archivesName = project.archives_base_name }

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(25) }
    withSourcesJar()
}
